### ISSUE TITLE
Unable to make setup

### ISSUE THREAD

**Issue by zejtin** [CapsCollective/a-dark-discomfort#9]
Hey guys,

when I try to run: **mingw32-make setup** I get the following error:

LATFORM=PLATFORM_DESKTOP
mingw32-make[1]: Entering directory 'C:/SVN/a-dark-discomfort/vendor/raylib-cpp/vendor/raylib/src'
gcc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
mingw32-make[1]: *** [Makefile:562: core.o] Error 1
mingw32-make[1]: Leaving directory 'C:/SVN/a-dark-discomfort/vendor/raylib-cpp/vendor/raylib/src'
mingw32-make: *** [Makefile:74: lib] Error 2

**Comment by J-Mo63** [comment]
Hi @zejtin, thanks for taking a look into the work! As I don't have a Windows machine, I can't quite help fix the issue fully, however the other maintainer, @Raelr, does. With that in mind, I'll get you started with diagnosing the problem so he can take over. Since it seems Windows is building in GitHub Actions, the questions I'll start with relate to your current setup:

1. It seems like you have a version of MinGW installed, however both MinGW 32bit and 64bit use the `mingw32-make` command. Could you let us know which version of the program you actually have installed on your system?

2. In addition, it would be good to check what version of the application you have, so if you could also let us know the result of running `g++ --version`, that would be helpful.

3. From the error message, this seems to be an issue with building raylib itself, so it might be a good idea to try manually building it from [this repo](https://github.com/raysan5/raylib) in order confirm it as being the source of the issue. This could be accomplished by running `mingw32-make PLATFORM=PLATFORM_DESKTOP` in its `raylib/src/` directory.

4. If that does indeed build, then we have a template repo this one is based on that you can try [here](https://github.com/CapsCollective/raylib-cpp-starter).

Good luck with those and let us know how it goes. I'm not going to mark this one as a bug until its confirmed as being an issue beyond your machine, however until then I'll assign my good friend and Windows-enthusiast @Raelr to this issue.

**Comment by J-Mo63** [comment]
@Raelr right before the crash, instead of:

> mingw32-make[1]: *** [Makefile:562: core.o] Error 1
> mingw32-make[1]: Leaving directory 'C:/SVN/a-dark-discomfort/vendor/raylib-cpp/vendor/raylib/src'
> mingw32-make: *** [Makefile:74: lib] Error 2

the output should have read (ignoring warnings):

> In file included from core.c:137:
> gcc -c shapes.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
> gcc -c textures.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
> gcc -c text.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33

Also seems like it errored out on the first object code compile, so keep in mind raylib's  `external/glfw/include`, `external/glfw/deps/mingw`, and OpenGL 3.3 as potential points of failure here.

**Comment by zejtin** [comment]
Hi @J-Mo63 ! Thanks for the quick response! I'm a huge fan of survival-horror genre and this definitely looks like an interesting project :)
Here are the answers:

1. I installed MinGW using chocolatey, this particular package https://chocolatey.org/packages/mingw 
Here is the output when I run `gcc --version`

```
gcc.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
```

2. Output for `g++ --version`

```
g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
```

3. and 4. Followed the instructions, but it doesn't work as you suspected

```
PS C:\SVN\raylib\src> mingw32-make PLATFORM=PLATFORM_DESKTOP
gcc -c core.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -s -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33
mingw32-make: *** [Makefile:561: core.o] Error 1
```

Maybe I should do the manual install of mingw32 @Raelr ?

Thanks once more guys :)

**Comment by Raelr** [comment]
Hey @zejtin,

Thanks for your response! 

I spun up a VM on my end and tried to replicate this but I wasn't able to get the same error. As my colleague, @J-Mo63 mentioned, this looks to be an issue with building the Raylib library specifically, which isn't too helpful, I'm afraid. 

Maybe this does have to do with the installation style? I installed mingw64 from this source: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download. I'm not convinced that the issue is with chocolatey, however it might still be worth trying to use the version in the link I supplied? 

As well as this, I do just want to give a little disclaimer - this is in SUPER early stages at the moment. We're currently in the midst of building up the core engine tools and graphics, and haven't even started on gameplay. You're more than welcome to give what we have a look, but it might be a little underwhelming as of now! 

Please let me know if a manual install of mingw32 helps!

**Comment by zejtin** [comment]
Sorry for the late reply guys! I'm in middle of moving to new flat 🏚️ 
Many thanks for reply! Will give it a go or just try it in linux in the end :) oooor, since i'm better with c# try to convert it to raylib-cs :D 

I know it is early phase but this looks super interesting nonetheless, keep up with great job!

**Comment by J-Mo63** [comment]
No worries @zejtin! Since this issue seems to be more relevant to the core of the project than any of the game's code, I'm going to go ahead and transfer it to the template repository it's based on.
